### ISSUE TITLE
Structure Definition expects String in StructureDefinition->ElementDefinition->Type->Profile but there will be a list

### ISSUE THREAD

**Issue by chrmey** [smart-on-fhir/client-py#103]
Screenshot from FHIR-Website: Element Definition

![grafik](https://user-images.githubusercontent.com/47111421/114697166-db130000-9d1d-11eb-82f6-89e47d5e7149.png)

As the FHIR website suggests there can be multiple values (a list) in this field. FHIR Client gives me an exception, stating that it is expecting a string for this field. 

Error Message:

```Wrong type <class 'list'> for property "profile" on <class 'fhirclient.models.elementdefinition.ElementDefinitionType'>, expecting <class 'str'>```

**Comment by mikix** [comment]
Thanks for the report!

I'm not sure what the state of things was in April 2021, but in the [current release](https://github.com/smart-on-fhir/client-py/blob/v4.1.0/fhirclient/models/elementdefinition.py#L1615) (and in main), the `profile` field is a string, but marked as `is_list` (the `True` right after the `str`).

So this should be working today at least. If it still isn't working for you, please re-open.
