### ISSUE TITLE
Cannot have a package named 'models' in project

### ISSUE THREAD

**Issue by RafaelWO** [smart-on-fhir/client-py#110]
I would like to have a directory/package called `models` within my project that uses this library. Sadly, this does not work.

Check out this minimal example:
```
.
├── main.py
└── models
    ├── bar.py
    └── __init__.py
```
```python
# models/bar.py
print("I'm bar!")
```
```python
# main.py
from models import bar
```
If I run `main.py` it gives the expected output:
```
I'm bar!
```

Now, I will import something from `fhirclient` in `main.py`:
```python
# main.py
from fhirclient import client

from models import bar
```
If I now run `main.py` I get the following error:
```
Traceback (most recent call last):
  File "/path/to/playground/main.py", line 2, in <module>
    from models import bar
ImportError: cannot import name 'bar' from 'models' (/path/to/fhirclient-package/fhirclient/fhirclient/models/__init__.py)
```

----

I guess this is due to adding the directory `models` in from `fhirclient` to `sys.path` in the [parent `__init__.py` file](https://github.com/smart-on-fhir/client-py/blob/master/fhirclient/__init__.py):
```python
# fhirclient/__init__.py
import sys
import os.path
abspath = os.path.abspath(os.path.dirname(__file__))
if abspath not in sys.path:
    sys.path.insert(0, abspath)
```

**Comment by mzbik** [comment]
This also happens with directory named "server".  It seems pretty odd practice for a module __init__ to futz with the system path...

**Comment by ducu** [comment]
Guys if you come up with a fix for this it would be great, looking fwd for pull requests.

**Comment by p2-apple** [comment]
I think the original hack with sys path was to support Python 2 and 3. You could consider finally dropping Python 2 and revamp all the imports.

I remember those being a headache, see e.g. https://github.com/smart-on-fhir/client-py/commit/7ee688abe250dfec2b3cce7c5739f96dd51dfc01

**Comment by ducu** [comment]
Yes dropping Python 2 could be the way to go, feel free to take this on

**Comment by mzbik** [comment]
See PR #134
