### ISSUE TITLE
Reauthorization does not work beyond the first attempt

### ISSUE THREAD

**Issue by timharsch** [smart-on-fhir/client-py#112]
When using this library to download a large number of documents/resources from Cerner sandbox, it became apparent that reauthorization fails for all but the first attempt.   This is because the refresh_token is lost when process the response from the remote host.  In Cerner's case, it does not return the refresh token in the response, and so the token is erased from the server instance referenced by `client.server`

In our case we only use the DSTU2 version of client-py and I don't see anything in the CONTRIBUTING.md document about how to target PRs, so I'll just leave my solution here (which is a commit added on top on the v1.0.6 tag)
https://github.com/Unite-Genomics/client-py/commit/c4f02e92a255ed09e2711f80e3b1d0ddd525589a

**Comment by ducu** [comment]
Hi @timharsch, pull requests are welcome, let me know if still interested

**Comment by timharsch** [comment]
PR created

**Comment by timharsch** [comment]
Will be opening a new PR soon that applies the fix to the master branch.

**Comment by timharsch** [comment]
Hi @ducu , the new PR is ready.  Can you merge please?
