### ISSUE TITLE
Provider Portal Launch Support?

### ISSUE THREAD

**Issue by ChrisMeeusen** [smart-on-fhir/client-py#131]
Hello, does this client library support the provider portal launch scenario?  I see how the FhirClient can be used to initiate a login flow with an ehr, but I'm not seeing how to use this library to receive a launch from an EHR.  Does this library consume the iss query string param that the EHR provides?

**Comment by mikix** [comment]
No - receiving a launch request from the EHR is left to the app, this library just helps with talking to the EHR for auth and resources.
