### ISSUE TITLE
description is not a required field for Conformance

### ISSUE THREAD

**Issue by timharsch** [smart-on-fhir/client-py#132]
This BUG is in the v1.0.6 tag and prevents using fhirclient to process records from the publc HAPI DSTU2 test server (see the conformance document at https://hapi.fhir.org/baseDstu2/metadata?_format=json).  And notice it does not provide a "description" in the "implementation" object.

![image](https://user-images.githubusercontent.com/61298249/191631712-9e808956-c0fd-48aa-abf1-9856b90d3ec7.png)

per: https://hl7.org/implement/standards/fhir/DSTU2/conformance-definitions.html#Conformance.implementation, description is not a required field

Attempting to make a connection to the HAPI server mentioned above will cause the following error:
![image](https://user-images.githubusercontent.com/61298249/191631822-801280a8-41be-4db4-be27-76d795e74a31.png)

The line of code that needs to be changed to fix this is here:
![image](https://user-images.githubusercontent.com/61298249/191632045-2d4bba1f-b451-4652-8beb-f715f600c355.png)

I'm happy to submit a PR, but I'll need to understand the release process for DSTU2 to do so.

**Comment by p2** [comment]
These classes are all generated from the spec. If you look closely at the link you provided, `implementation.description` is indeed `1..1`, meaning it _is_ required if `implementation` is present.

**Comment by timharsch** [comment]
Ah, I see I misread the 0..1 for Conformance.implementation, and this statement made me think it was to Conformance.implementation.description, but I think it must have meant Conformance.description
>SHALL have at least one of description, software, or implementation 

I think this means then, that the HAPI Conformance doc has a bug.  And also that there is a bug in master (R4) since [CapabilityStatement.implementation.description](https://hl7.org/implement/standards/fhir/R4/capabilitystatement-definitions.html#CapabilityStatement.implementation.description) also states 1..1

See this line of code from master, which has False for the last parameter:
https://github.com/smart-on-fhir/client-py/blob/master/fhirclient/models/capabilitystatement.py#L247

**Comment by timharsch** [comment]
The problem has been address in the DSTU2 HAPI test server, so it should be possible to connect and fetch resources from that server now.

Closing this issue.

https://github.com/hapifhir/hapi-fhir/pull/4082
