### ISSUE TITLE
Bundles are not being posted to the base API path

### ISSUE THREAD

**Issue by RadovanTomik** [smart-on-fhir/client-py#141]
### Description

Trying to post a Bundle Resource of type "transaction" results in it being posted to BASE_API/Bundle therefore resources that are part of the bundle are not created.

### How to reproduce

Create a Bundle resource of type 'transaction' and resource_type 'Bundle'. Try to post it to a FHIR server using `bundle.create(server)`

### What happens

The bundle can be found at BASE_API/Bundle and the resources in it have not been created on the FHIR server

### What should happen

The bundle should be posted to just BASE_API and the resources in bundle.entries should be created/updated.

**Comment by mikix** [comment]
This sounds like it was fixed in the (unreleased yet) #105 change. I'll close with that assumption, but please re-open if not.
