### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by czue** [smart-on-fhir/client-py#146]
I was excited to find this project but it seems very inactive. Lots of open pull requests for simple things like version bumps not being merged or reviewed.

Is this project dead? And if so, is there a recommended alternative?

**Comment by ducu** [comment]
Hi @czue, are you willing to take over the project?

**Comment by czue** [comment]
Hi @ducu - thanks for the response! I've made some modifications/updates and would be happy to work with the maintainers to get them merged back in. In terms of taking over the project, I don't think I'm a good fit because I'm unlikely to be using it long term, but I'd be happy to check with my company and see if they are interested if you are looking for a new home for it?

**Comment by ducu** [comment]
Yes sorry I don't have the time to maintain this project, not using anymore.
I was added as maintainer but not admin, can't add other people, if anyone wants that please contact jmandel@alum.mit.edu

Anyway if you want any particular PR merged please let me know

**Comment by dogversioning** [comment]
For posterity - after discussing this with Josh, the SMART Cumulus team is going to help with some TBD level of maintenance for this repo - we'll start with the security updates while we figure out what we've got bandwidth for.
