### ISSUE TITLE
Cannonical types being parsed as the underlying object rather than string URI

### ISSUE THREAD

**Issue by dogversioning** [smart-on-fhir/client-py#173]
Fields like [the description field in a rest resource operation](https://www.hl7.org/fhir/R4/capabilitystatement-definitions.html#CapabilityStatement.rest.resource.operation.definition) are specified as being cannonical references, but it looks like fhirclient is parsing them expecting the underlying object, resulting in errors like this:

```fhirclient.models.fhirabstractbase.FHIRValidationError: {root}:
  rest.0:
    operation.0:
      definition:
        Wrong type <class 'str'> for property "definition" on <class 'fhirclient.models.capabilitystatement.CapabilityStatementRestResourceOperation'>, expecting <class 'dict'>
```
        
We should, at a bare minimum, allow the string URI to be correctly parsed in this field. If possible, we might want to try looking the reference up, and building out the appropriate model as a result?

It may be worth looking back at the delta between 4.0.0 and 4.0.1, since this seems to only happen on the latest rev of v4.

Observed against https://r4.smarthealthit.org/metadata

**Comment by mikix** [comment]
This seems like it was an odd misconfiguration - Matt and I can't reproduce with fresh environments.
