### ISSUE TITLE
Add support for logging FHIR requests

### ISSUE THREAD

**Issue by erikwiffin** [smart-on-fhir/client-py#18]
As part of the S4S project (http://syncfor.science/), we'd like to be able to log all of our FHIR requests so that we can see how various API implementations are changing over time. Right now, this doesn't seem possible using the fhirclient library.

The obvious hook for this behavior would be in `FHIRServer._get`, but there's a lot of different ways this could be accomplished. The easiest in my mind is some kind of `last_response` property on the FHIRServer class.  Any time a call to one of the request methods is made, the response would be set to `last_response` before `res.json()` is returned. My calling code would then be responsible for accessing that property and storing it somewhere.

A more involved solution would be some kind of HTTP'er class that FHIRServer would use for any of its HTTP related behavior instead of calling the requests library directly. Then I could write my own logging-aware HTTP'er and provide that to my FHIRServer instance instead of the default one that would ship with this library. This could also potentially make it easier to resolve some of the issues raised in https://github.com/smart-on-fhir/client-py/pull/16, having auth.py set up some kind of SecureHTTP'er maybe? I haven't thought that use case through very well, but modularization is always helpful. ;)

**Comment by erikwiffin** [comment]
A less involved version of my HTTP'er class would be to store a requests [Session](http://docs.python-requests.org/en/master/api/#requests.Session) somewhere in the FHIRServer and use that for HTTP requests. Then I'd be able to use the event hooks native to requests to log things. IMO this is probably a good balance between weight to this library and added functionality.

**Comment by p2** [comment]
What exactly do you want to log? The _requests_ module already uses `logging` extensively, maybe that's a place to hook in?

**Comment by erikwiffin** [comment]
I want to log basically everything, the sent headers/body/other metadata and the response headers/body/metadata. The body in particular, I don't think is available through the existing logs.

**Comment by p2** [comment]
Is that all possible with your suggested `requests.Session` approach?

If not, an alternative may be to simply implement `logging` in the server methods.

**Comment by erikwiffin** [comment]
Yep, exposing the session is working perfectly.
