### ISSUE TITLE
FHIR headers not set for create, update, delete

### ISSUE THREAD

**Issue by bktrinadh** [smart-on-fhir/client-py#22]
Hi:
I was trying to save the FHIR object. It was failing and when I debugged the reason, I figured out that there was no FHIR headers set like in _get() method.. Here is the snip that I have added and the save is working.. I wanted to know if there is any reason why it is not set like in get method..
        if self.auth is not None and self.auth.can_sign_headers():
            headers = self.auth.signed_headers(headers)
Thanks
Trinadh..

**Comment by p2** [comment]
That definitely was an omission, thanks for reporting. Hope it works well now!

**Comment by bktrinadh** [comment]
Its working.. Thank you..

**Comment by karlanke** [comment]
Any chance this could get back-ported to v1?
