### ISSUE TITLE
change logging mechanism and debug of FHIR operations

### ISSUE THREAD

**Issue by bktrinadh** [smart-on-fhir/client-py#25]
Hi:
This is an enhancement request.

Currently fhirclient relies on root logger configuration to log messages. In my application the root configuration is set to warning. There is no way to enable DEBUG for fhirclient only.. Can the logging be changed to:

    import logging
    logger = logging.getLogger(__name__)

Also I feel requests_toolbelt.utils.dump can be used to debug the responses from ehr server. Is it possible to include the library in requirement and enable the debug like below (I use in debug mode):

        from requests_toolbelt.utils import dump
        res = self.session.put(url, headers=headers, data=json.dumps(resource_json))
        logging.debug('SMART SERVER:\r\n{0}'.format(dump.dump_response(res).decode('utf-8')))
        self.raise_for_status(res)

Thanks
Trinadh..

**Comment by p2** [comment]
Yes, sounds good, happy to accept a PR.
