### ISSUE TITLE
Syntax Error in fhirsearch.py 

### ISSUE THREAD

**Issue by bktrinadh** [smart-on-fhir/client-py#35]
Hi,

Is there a syntax error in fhirsearch.py, class=FHIRSearchParamOperatorHandler, method=apply

```
    def apply(self, param):
        if self.key not in self.__class__.operators:
            raise Exception('Unknown operator "{}" for "{}"'.format(self.key, parent.name))
        param.value = self.__class__.operators[self.key] + self.value
```

Should be raise Exception('Unknown operator "{}" for "{}"'.format(self.key, **param**.name))

Thanks
Trinadh..

**Comment by mikix** [comment]
Fixed by the above PR, this issue just never got closed.
