### ISSUE TITLE
Ability to use fhirclient for DSTU2 as well as DSTU3

### ISSUE THREAD

**Issue by bktrinadh** [smart-on-fhir/client-py#36]
Hi,

I am not sure if there is a way one can use the fhirclient for DSTU2 as well as STU3? The current master is updated with STU3. I want to pick the latest code but use models from DSTU2. If there is a way of specifying the version while creating the FHIRClient by passing in the version that one want to use would be great..

Thanks
Trinadh..

**Comment by p2** [comment]
Which code from STU-3 do you wish to use with DSTU-2 models?

Out of the box this is not possible. You can check out master from before the STU-3 merge and update the code that you want changed by hand.
