### ISSUE TITLE
Unhelpful error message on malformed conformance statement.

### ISSUE THREAD

**Issue by erikwiffin** [smart-on-fhir/client-py#39]
This affects [v1.0.6](https://github.com/smart-on-fhir/client-py/releases/tag/v1.0.6).

If the conformance statement parser is provided a null when it expects an object, the error message is confusing.

I was attempting to load a conformance statement where conformance.rest.resources had nulls in the searchTerms array. See https://gist.github.com/erikwiffin/cdcb94b0228a081c510d554a921cdc8d. When I tried to load the conformance statement, I got the following error message:

```
FHIRValidationError: {root}:
  rest:
    resource:
      searchParam:
        name 'self' is not defined
```

I can't quite follow the logic in https://github.com/smart-on-fhir/client-py/blob/v1.0.6/fhirclient/models/fhirabstractbase.py, but it looks like something in `update_with_json` isn't correctly checking that it has a dictionary instead of a None. A check so that a more accurate error message could be displayed would be really helpful. Also, the tree `rest.resource.searchParam` feels like it skipped a step. Something to indicate which resource is causing the problem, whether that be an array index or the resource type would make that a lot more legible.

I realize this is an issue with an older version of the client library, but my FHIR server is still DSTU2 and 3.0.0 can't read that at all.

**Comment by p2** [comment]
Error reporting has indeed been improved in the newer versions, e.g. with added array indices. You'd have to backport the changes from `fhirabstractbase`.

**Comment by p2** [comment]
FWIW, you can use `fhirabstractbase.py` from 3.0.0 in 1.0.6, you only need to change `resource_type` to `resource_name` in `owningBundle(self)` on line 328.
