### ISSUE TITLE
Search in FHIR

### ISSUE THREAD

**Issue by janadh** [smart-on-fhir/client-py#4]
I am trying to search a patient using given name through a local server. this is my code. Local server's authentication is turned off. 

###### in the  view class of django framework

from fhirclient import client
from fhirclient.models.patient import Patient as fhir_patient
from fhirclient.server import FHIRServer
from fhirclient.models.fhirsearch import FHIRSearch

###### in one of the view function I tried to search for patient. First with id(this works) then using search(does not work).

server = FHIRServer( request, base_uri="http://localhost:8080")
patient = fhir_patient.read("1098667", server)
#The above code works and I can read the patient details. 

fs = FHIRSearch(fhir_patient,{"given":"rob"})
r = fs.perform_resources(server)

### I get a list with 1 object with None type...
![image](https://cloud.githubusercontent.com/assets/10822455/9347344/17a8220e-465b-11e5-8723-624823518bcd.png)

So looking deep into the code , I can confirm that I get the expected server response. But the bundle class is not reading it. 

###more of my inspection..
in server.py
value of the url is 'http://localhost:8080/Patient?given=rob' 

the response from the server is as follows. (ie res._content variable )

{
  "resourceType": "Bundle",
  "title": "FHIR Atom Feed",
  "id": "http://localhost:9080/Patient?given=rob",
  "link": [
    {
      "rel": "self",
      "href": "http://localhost:9080/Patient?given=rob"
    }
  ],
  "totalResults": 1,
  "updated": "2015-08-19T10:07:21.063+08:00",
  "author": [
    {
      "name": "groovy.config.atom.author-name",
      "uri": "groovy.config.atom.author-uri"
    }
  ],
  "entry": [
    {
      "title": "Patient/1098667",
      "id": "http://localhost:9080/Patient/1098667",
      "updated": "2015-08-19T10:07:21.063+08:00",
      "content": {
        "resourceType": "Patient",
        "text": {
          "status": "generated",
          "div": "<div>\n        \n            <p>Robert Hill</p>\n      \n          </div>"
        },
        "identifier": [
          {
            "use": "usual",
            "label": "SMART Hospital MRN",
            "system": "urn:oid:0.1.2.3.4.5.6.7",
            "value": "1098667"
          }
        ],
        "name": [
          {
            "use": "official",
            "family": [
              "Hill"
            ],
            "given": [
              "Robert",
              "P."
            ]
          }
        ],
        "telecom": [
          {
            "system": "email",
            "value": "robert.hill@example.com"
          }
        ],
        "gender": {
          "coding": [
            {
              "system": "http://hl7.org/fhir/v3/AdministrativeGender",
              "code": "M",
              "display": "Male"
            }
          ]
        },
        "birthDate": "1953-10-27",
        "address": [
          {
            "use": "home",
            "line": [
              "42 Park St"
            ],
            "city": "Bixby",
            "state": "OK",
            "zip": "74008",
            "country": "USA"
          }
        ],
        "active": true
      }
    }
  ]
}

###########################

But the bundle class always respond with 1 entry with a None type. Image is attached. Am I doing something wrong. ?

**Comment by p2** [comment]
The bundle response is not valid. The patient resource is expected to be in `Bundle.entry.resource`, in your example it is directly in `Bundle.entry`.

Would be good to add error logging...

**Comment by janadh** [comment]
I just check it at 
http://fhir.healthintersections.com.au/open/Patient?given=carl&_format=json
_________
![image](https://cloud.githubusercontent.com/assets/10822455/9349226/56be5642-4675-11e5-86da-aa9c81d4f442.png)
________

Which is same as what I get from the local server (I used smart on fhir api-server ). ie: the patients are returned directly inside bundle.entry as a list. Sorry I am not sure which class to add the error log as I am a newbie. Any help is appreciated.

**Comment by p2** [comment]
I think that's a DSTU1 server, can you try with a DSTU2 server? For example ours at https://fhir-api-dstu2.smarthealthit.org ?

Or you have to check out the DSTU-1 release of this client, which is less feature complete.

The _logging_ was a note to myself. :)

**Comment by janadh** [comment]
Hi Pascal, Thanks for the direction. IT WORKED.
the updated code....

	server = FHIRServer( request, base_uri="https://fhir-open-api-dstu2.smarthealthit.org")
	fs = FHIRSearch(fhir_patient,{"given":"rob"})
	r = fs.perform_resources(server)

Note: Initially it didn't work because of auth. So I guessed the open auth server name and it worked. When using
server = FHIRServer( request, base_uri="http://fhir-dev.healthintersections.com.au/open/") 
it does work but you have to be sure to add the trailing backslash. Not sure why. 

Anyways is there are any chance to get a local copy of your dstu2 server? 
  
cheers
Jana

**Comment by p2** [comment]
Ah right, need to update to also work without trailing backslash, thanks for figuring this out.

You can find an installer for our server stack in our GitHub account, can't check right now.
