### ISSUE TITLE
human_name function in  client-py/fhirclient/client.py gives error in some cases

### ISSUE THREAD

**Issue by dksr** [smart-on-fhir/client-py#40]
Hi,
The function human_name() in client.py does not behave properly for some patient examples.  The test example I tried is:

from fhirclient import client
import fhirclient.models.patient as p

settings = {
     'app_id': 'my_web_app',
     'api_base': 'https://sb-fhir-stu3.smarthealthit.org/smartstu3/open'
     }
smart = client.FHIRClient(settings=settings)
patient = p.Patient.read('44a35c47-72b1-4e49-bb1e-518b0abedd65', smart.server)
print (smart.human_name(patient.name[0]))

Example data:
-------------------
"name": [
    {
      "use": "official",
      "family": "Abbott",
      "given": [
        "Gonzalo"
      ],
      "prefix": [
        "Mr."
      ]
    }

The reason the function fails is that it expects all prefix, given, family names as lists whereas family name is definitely not a list at shown above. Also some times the suffix is None and this is not tested in the function before use and so gives error.

- Krishna

**Comment by rdsteed** [comment]
Had a similar problem.  Happened because fhir schema changed.  Solution was to match the pyclient version to the server.

**Comment by boristyukin** [comment]
had the same issue. It would be awesome if one can actually specify FHIR version for models / validators. if someone has to work with multiple FHIR sources/vendors, there needs to be multiple versions of fhir client installed which is a pain to support / upgrade.

**Comment by p2** [comment]
This issue has been fixed in #42 

@boristyukin , you can have two separate checkouts in different directories and import both to a different namespace, e.g. `fhir2` and `fhir3`, then use accordingly.

**Comment by boristyukin** [comment]
@p2 thanks so much, can you explain how? do you mean to clone/install two different versions of client and import one of them depending on a version of FHIR needed? My concern in that case for older version of client I would not get all the recent fixes / enhancements while retaining compatibility with FHIR version

**Comment by p2** [comment]
Yes, clone them into different directories with the names you like and import the right one. Yes, you won't get the recent fixes / enhancements.

Another way would be to generate the data models of the version you need yourself by changing `specification_url` in [`fhir-parser-resources/settings.py`](https://github.com/smart-on-fhir/client-py/blob/master/fhir-parser-resources/settings.py), but that may not work depending on how old the version is that you need and I'm unable to provide support for that.
