### ISSUE TITLE
fhirclient-1.0.6 cannot create new resources on server

### ISSUE THREAD

**Issue by lynchdennis94** [smart-on-fhir/client-py#44]
When using the create function on fhirabstractresource classes, the path passed to the server.put_json() function is the relative path, not the relative base.  When attempting to use fhirclient-1.0.6 with a FHIR 1.6.0 server, this results in a PUT request to a Patient/None endpoint, failing the addition.  In the current master branch this issue has been fixed, but the code pulled from the 1.0.6 apt repository still has this bug.

**Comment by mikix** [comment]
The working code in the master branch referenced has been released
