### ISSUE TITLE
normalize fhir model classes

### ISSUE THREAD

**Issue by boristyukin** [smart-on-fhir/client-py#45]
Pascal I apologize if this question does not relate exactly to this project but I cannot figure out how to contact you directly. I am playing with fhir client model classed and they are great but I am wondering if there is an easy way with client or maybe some other project that would allow normalizing resources into flat structures so they can be loaded to RDBMS. One idea I have is to somehow use your fhir model parser / generator to generate table DDLs and appropriate mappings. For example, patient resource will turn into multiple flat structures (table like) such as patient, patient_name, patient_identifiers etc. Hope it makes sense

**Comment by p2** [comment]
I don't have good advice for you, but you may be interested in FHIRBase: http://fhirbase.github.io
