### ISSUE TITLE
SOLVED: 406 HTTP errors using mismatched `fhirclient` version and FHIR endpoint

### ISSUE THREAD

**Issue by pacharanero** [smart-on-fhir/client-py#48]
Not really an issue with this code, but just signpost for others having similar troubles:

We were attempting to contact the Cerner unauthenticated demo/sandbox FHIR server at https://fhir-open.sandboxcerner.com/dstu2/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca using this fhirclient library. This is a DSTU2 version FHIR server so we should have maded sure we were using the correct version of `fhirclient`,  however we thought we'd try with the `master` branch initially.

The Cerner server seems very sensitive to being passed only the _correct_ `'Accept': 'application/json+fhir'` header, and will refuse to interact if the header is `'Accept': 'application/fhir+json'`. 

The error received is factually accurate but didn't particularly aid us in finding the problem: (included here for Googleability)
```
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url
```
Postman's error when passing similar invalid headers is coming back from the server and is a little more detailed:
```
The Accept type is invalid. See the documentation on the fhir.cerner.com website for acceptable format values for the resource you are attempting to access.
```

It's our own fault for not using the right version of the library, but we wasted a good hour trying to work out what the problem was and then figuring out how to pass a different header using `fhirclient`, when all we _really_ needed to do was:

```
pip install fhirclient==1.0.3
```

**Comment by p2** [comment]
Yes – see the version matrix in the README for correct versions. 👍🏼

**Comment by Lyelt** [comment]
Thank you for this. I probably would've spent multiple hours trying to figure this out.
