### ISSUE TITLE
in models strict=False does not turn off validation as expected

### ISSUE THREAD

**Issue by Healthedata1** [smart-on-fhir/client-py#50]
in models strict=False parameter does not turn off validation as I expected. 
~~~
>>> import fhirclient.models.observation as O
>>> o = O.Observation(strict=False)
>>> o.as_json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ehaas/Documents/testing/pyexcel/venv36/lib/python3.6/site-packages/fhirclient/models/fhirabstractresource.py", line 42, in as_json
    js = super(FHIRAbstractResource, self).as_json()
  File "/Users/ehaas/Documents/testing/pyexcel/venv36/lib/python3.6/site-packages/fhirclient/models/fhirabstractbase.py", line 297, in as_json
    raise FHIRValidationError(errs)
fhirclient.models.fhirabstractbase.FHIRValidationError: {root}:
  'Property "code" on <fhirclient.models.observation.Observation object at 0x1022975c0> is not optional, you must provide a value for it'
  'Property "status" on <fhirclient.models.observation.Observation object at 0x1022975c0> is not optional, you must provide a value for it'
~~~

**Comment by Healthedata1** [comment]
I stumbled on the try except pattern,  but that doesn't let me see the
ill-formed or half baked json.   For example, I'm creating an resource and
want to inspect it halfway -  how do I get a look a the json if I can't
just .as_json it?

Eric

Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by Healthedata1** [comment]
Thanks for the response by the way.

Eric

Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by p2** [comment]
It's not currently possible to create invalid JSON with `as_json()`. Could consider extending that method with a `strict=True` argument and not raising if strict is `False` towards the end of the implementation. But I'm not sure I see the use-case, do you need to inspect the JSON before it's valid?

**Comment by Healthedata1** [comment]
my case is  literally

logging.Info('my resource foo looks like {}'.format(resource.as_json())

but on the  other hand it is easy to work around.   thiinking about it -I'd
keep it the way it is.


Eric



Eric M Haas, DVM, MS
Health eData Inc
1183 Mountain View Circle, Napa, 94558
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by mikix** [comment]
Cleaning up old tickets, and since this seemed to resolve in a "let's leave it like it is", I'll close
