### ISSUE TITLE
Quantity does not accept integers

### ISSUE THREAD

**Issue by hheldenbrand** [smart-on-fhir/client-py#51]
I know similar issues have already been raised (e.g. https://github.com/smart-on-fhir/client-py/issues/33) but wanted to add that the mapping of the python type 'float' to quantity.value causes valid integer values to be rejected.

In this example: http://hl7.org/fhir/medicationdispense0303.json.html the values in daysSupply and quantity would incorrectly raise FHIRValidationErrors as type str when float is expected.

**Comment by p2** [comment]
This seems to work for me with version `3.0.0`?

```
$ python
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
>>> import json
>>> with open('medicationdispense0303.json', 'r') as h:
...     js = json.load(h)
>>> from fhirclient.models import medicationdispense as _MD
>>> md = _MD.MedicationDispense(js)
>>> md.daysSupply
<fhirclient.models.quantity.Quantity object at 0x10a8cd358>
>>> md.daysSupply.value
10
```

**Comment by hheldenbrand** [comment]
Thanks for the response and clear example code.  You are correct and your example helped me find the issue further upstream in my own code.
