### ISSUE TITLE
Test server in README.md does not work

### ISSUE THREAD

**Issue by nerdoc** [smart-on-fhir/client-py#55]
I just tried your example in [README.md](https://github.com/smart-on-fhir/client-py/blob/master/README.md) - the server is unavailable. Is there another URL available for testing?

**Comment by p2** [comment]
Yes, there are many. Make sure to pick a server that uses the correct FHIR version!

http://wiki.hl7.org/index.php?title=Publicly_Available_FHIR_Servers_for_testing

**Comment by ec-wagner** [comment]
Can some one suggest a server that works, please.

**Comment by p2** [comment]
https://test.fhir.org/r3
https://test.fhir.org/r4

See #38
