### ISSUE TITLE
module 'fhirclient.models.medication' has no attribute 'read'

### ISSUE THREAD

**Issue by JMathiszig-Lee** [smart-on-fhir/client-py#56]
Taking my first steps with adding some Fhir goodness to an application i've been working on. 

Everything has gone well so far and was up and running with some basic queries but ran into problems taking things further to be more usable. 

`import fhirclient.models.medicationrequest as meds
import fhirclient.models.medication as mednames`

search = meds.MedicationRequest.where(struct={'subject': '2c4c5104-6d23-4c0a-97e9-bd229fc3559c', 'status': 'active'})
    medications = search.perform_resources(smart.server)`

this appropriately returns two resources with a references:
-Medication/97e9b032-aad0-4c3e-9143-bb9e145c0491
-Medication/2c1ca733-3562-497a-82fa-ca6218258314 

however 

`for medication in medications:
        medref = medication.medicationReference.reference
        med = mednames.Medication.read(medref, smart.server)
`
 returns the error that 

> module 'fhirclient.models.medication' has no attribute 'read'

Goal is to produce a list of the actual names of the medication the patient is on so it might be i'm going about it the wrong way but this seems to be the way implied by the documentation.

**Comment by p2** [comment]
You can just use the `resolved()` method on any reference to get the referenced resource, like so:

```
med = medication.medicationReference.resolved(mednames.Medication)
```
