### ISSUE TITLE
FHIRValidationError:

### ISSUE THREAD

**Issue by tvk66866** [smart-on-fhir/client-py#63]
<from fhirclient import client
settings = {
    'app_id': 'first_fhir',
    'api_base': 'https://syntheticmass.mitre.org/fhir/'
    #https://syntheticmass.mitre.org/fhir/Patient/58b3663e3425def0f0f6a229/$everything
}
smart = client.FHIRClient(settings=settings)
import fhirclient.models.observation as o
ob_data = o.Observation.read('58b3663e3425def0f0f69522',smart.server)
ob_data >

Got error: 
FHIRValidationError: {root}:
  Superfluous entry "encounter" in data for <fhirclient.models.observation.Observation object at 0x0000026A163A8390>

**Comment by fiendish** [comment]
same with    `'api_base': 'https://r4.smarthealthit.org'`

**Comment by mikix** [comment]
Going to optimistically close this now that 4.1.0 is on pypi
