### ISSUE TITLE
'https://sb-fhir-stu3.smarthealthit.org/smartstu3/data' is not working

### ISSUE THREAD

**Issue by r76941156** [smart-on-fhir/client-py#65]
Hello everyone,

I tried to use the above site for Flask demo app (python), but it keeps showing 

"Operation timed out"

Do you know any other different sites? Thanks.

**Comment by raheelsayeed** [comment]
The endpoint in the sample flask app is old. The newer SMART sandbox is listed in the [launcher](https://launch.smarthealthit.org).

You can replace the url with either of these:

- open: `https://r3.smarthealthit.org`
- protected: `https://launch.smarthealthit.org/v/r3/fhir`

**Comment by gadepallivs** [comment]
@raheelsayeed , I am using the open api to test with the flask_app.py example. I get an error in the browser as follows. 
> Wrong type <class 'dict'> for property "profile" on <class 'models.capabilitystatement.CapabilityStatementRestResource'>, expecting <class 'str'>
'Non-optional property "kind" on <models.capabilitystatement.CapabilityStatement object at 0x00000205E3C82D88> is missing'

These are the modules installed in my active virtual environment 
```
Package      Version
------------ -------
Beaker       1.10.0
certifi      2019.6.
chardet      3.0.4
Click        7.0
fhirclient   3.2.0
Flask        1.1.1
idna         2.8
isodate      0.6.0
itsdangerous 1.1.0
Jinja2       2.10.1
MarkupSafe   1.1.1
pip          19.2.2
requests     2.22.0
setuptools   40.8.0
six          1.12.0
urllib3      1.25.3
Werkzeug     0.15.5
```

**Comment by Prolasis** [comment]
I think we are all getting an error,I also placed the open non auth server as the pointer and still error on auth. Is anyone able to assist 

`requests.exceptions.ConnectionError
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))`

**Comment by p2** [comment]
https://test.fhir.org/r3
https://test.fhir.org/r4

See #38

**Comment by kpoman** [comment]
Hello, trying to test from a git checkout. Testing different url's with different errors.

- 'api_base': 'https://r3.smarthealthit.org',

> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:23] "GET / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/beaker/middleware.py", line 156, in __call__
>     return self.wrap_app(environ, session_start_response)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/kpoman/Dev/client-py/flask_app.py", line 90, in index
>     auth_url = smart.authorize_url
>   File "/home/kpoman/Dev/client-py/fhirclient/client.py", line 124, in authorize_url
>     return self.server.authorize_uri if self.server is not None else None
>   File "/home/kpoman/Dev/client-py/fhirclient/server.py", line 116, in authorize_uri
>     self.get_capability()
>   File "/home/kpoman/Dev/client-py/fhirclient/server.py", line 84, in get_capability
>     conf = capabilitystatement.CapabilityStatement.read_from('metadata', self)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractresource.py", line 110, in read_from
>     instance = cls(jsondict=ret)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/capabilitystatement.py", line 134, in __init__
>     super(CapabilityStatement, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/domainresource.py", line 42, in __init__
>     super(DomainResource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/resource.py", line 42, in __init__
>     super(Resource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractresource.py", line 25, in __init__
>     super(FHIRAbstractResource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractbase.py", line 66, in __init__
>     self.update_with_json(jsondict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractbase.py", line 231, in update_with_json
>     raise FHIRValidationError(errs)
> models.fhirabstractbase.FHIRValidationError: {root}:
>   rest.0:
>     operation.0:
>       definition:
>         Wrong type <class 'dict'> for property "definition" on <class 'models.capabilitystatement.CapabilityStatementRestResourceOperation'>, expecting <class 'str'>
>     resource.0:
>       profile:
>         Wrong type <class 'dict'> for property "profile" on <class 'models.capabilitystatement.CapabilityStatementRestResource'>, expecting <class 'str'>
>   Superfluous entry "acceptUnknown" in data for <models.capabilitystatement.CapabilityStatement object at 0x7f27756c0a50>
> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:23] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:23] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:23] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:24] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> INFO:werkzeug:127.0.0.1 - - [07/May/2020 07:47:24] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 

- https://test.fhir.org/r4

> Traceback (most recent call last):
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/beaker/middleware.py", line 156, in __call__
>     return self.wrap_app(environ, session_start_response)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/kpoman/Dev/client-py/venv/lib/python3.7/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/kpoman/Dev/client-py/flask_app.py", line 90, in index
>     auth_url = smart.authorize_url
>   File "/home/kpoman/Dev/client-py/fhirclient/client.py", line 124, in authorize_url
>     return self.server.authorize_uri if self.server is not None else None
>   File "/home/kpoman/Dev/client-py/fhirclient/server.py", line 116, in authorize_uri
>     self.get_capability()
>   File "/home/kpoman/Dev/client-py/fhirclient/server.py", line 84, in get_capability
>     conf = capabilitystatement.CapabilityStatement.read_from('metadata', self)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractresource.py", line 110, in read_from
>     instance = cls(jsondict=ret)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/capabilitystatement.py", line 134, in __init__
>     super(CapabilityStatement, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/domainresource.py", line 42, in __init__
>     super(DomainResource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/resource.py", line 42, in __init__
>     super(Resource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractresource.py", line 25, in __init__
>     super(FHIRAbstractResource, self).__init__(jsondict=jsondict, strict=strict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractbase.py", line 66, in __init__
>     self.update_with_json(jsondict)
>   File "/home/kpoman/Dev/client-py/fhirclient/models/fhirabstractbase.py", line 231, in update_with_json
>     raise FHIRValidationError(errs)
> models.fhirabstractbase.FHIRValidationError: {root}:
>   rest.0:
>     resource.0:
>       searchParam.1:
>         'Non-optional property "type" on <models.capabilitystatement.CapabilityStatementRestResourceSearchParam object at 0x7f3b49e607d0> is missing'

some other ones do not respond.

**Comment by Prolasis** [comment]
I am also getting this error, and issue not resolved because the default server and some other info needs to be updated. I dont think anyone has a working version i know of.
