### ISSUE TITLE
pip install fhirclient does not include latest (4.0.0) version

### ISSUE THREAD

**Issue by Healthedata1** [smart-on-fhir/client-py#70]
the latest you pip install is 3.2.0  please load the latest to pip.

**Comment by yunwwang** [comment]
When will 4.0.0 available in pip?

**Comment by aadejare** [comment]
This is a major issue.  Finding out that I've worked with an older client has made me pause SMARTonFHIR integration.  Do we know when it will be resolved?

**Comment by hsolbrig** [comment]
We're hoping to resolve this in the next couple of weeks.  I am wanting to propose that we separate the current client.py into three modules:
* The FHIR python generator software -- takes any version/release of FHIR and generates the set of classes that represent it.
* The generated software -- the result of applying the software to DSTU3, R4, selected R5 checkpoints.  Each of these would be distributed as a PIP release.
* The Smart Client tools -- the SMART API that uses the generated software to act as an actual client.

Does this make sense to everyone?  If so, we can move fairly quickly to make it so.

**Comment by aadejare** [comment]
I think it does since there's been talk on [Google groups](https://groups.google.com/forum/#!topic/smart-on-fhir/pqwmqTMYIzk) about getting that support.  With that said, I would also think about trying to update the now outdated tutorial.

**Comment by hsolbrig** [comment]
Can you point me at the tutorial you are referencing?

**Comment by aadejare** [comment]
> Can you point me at the tutorial you are referencing?

Yep, [here](http://docs.smarthealthit.org/client-py/) which I don't think is a full tutorial but at least a getting started page.

**Comment by yunwwang** [comment]
After four months, this is still not resolved?

**Comment by hsolbrig** [comment]
'ang on -- we're getting there

**Comment by eldruin** [comment]
Is the proposed architecture change actually a blocker to publishing the already tagged version 4.0.0 on PyPI?
Internally we are moving ahead with using the 4.0.0 version as tagged here on GH. Maybe other people already do so as well given the age of the tag so a scenario where the current 4.0.0 tag is yanked and updated to a newer commit sounds like unexpected downstream breakage.

**Comment by pchakravarthy** [comment]
@hsolbrig Can we push the new version 4.0 to pypi. As @eldruin pointed out it would be great to release the 4.0 version to pypi and do the re-architecture as you mentioned.

**Comment by hsolbrig** [comment]
Will catch it next week.

**Comment by ekrempel** [comment]
Please consider updating the version in pip asap. I just lost 2 hours not realizing that I try using version of 3.2 of fhirclient with an HAPI server using R4 instead of DSTU3.

**Comment by henrym6003** [comment]
> We're hoping to resolve this in the next couple of weeks. I am wanting to propose that we separate the current client.py into three modules:
> 
> * The FHIR python generator software -- takes any version/release of FHIR and generates the set of classes that represent it.
> * The generated software -- the result of applying the software to DSTU3, R4, selected R5 checkpoints.  Each of these would be distributed as a PIP release.
> * The Smart Client tools -- the SMART API that uses the generated software to act as an actual client.
> 
> Does this make sense to everyone? If so, we can move fairly quickly to make it so.

I agree, this would be consistent with the hapi-fhir project.  Any ETA?

**Comment by sbwhitney** [comment]
> Will catch it next week.

Any status update on updating to version R4 in Pypi?

**Comment by philipstreck** [comment]
@hsolbrig I understand changes are underway architecturally however a release of 4.0 to pip in the interim would build valuable to many organizations developing Python FHIR applications in the immediate time frame. If this is not an option is there anything community members can help with to provide assistance?

**Comment by palfrey** [comment]
@hsolbrig @Culby Any updates on this? It would be really good to get a 4.0 release out, even if it's just a snapshot of the current master.

**Comment by singleplayer88** [comment]
@BrianKolowitz @hsolbrig +1, it would be really handy to have version 4.0 in pip

**Comment by SanderSu20** [comment]
Any update on this?

Thanks.

**Comment by danielcoam** [comment]
@hsolbrig Any news with that?
The current version on PyPI (3.2.0) is incompatible with the FHIR v4.

Please update about status,

Thanks

**Comment by emil45** [comment]
Guys come on, just upload the the new version.
Our production stuck because of that version issue.

**Comment by sbwhitney** [comment]
@danielcoam @emil45 this required a bunch of work but we refactored to leverage fhir.resources instead.

**Comment by danielcoam** [comment]
@sbwhitney Thanks for the reply.

Can you explain?

Do you mean to use the server (for example with post_json) but to build the model with the fhir.resources package?

**Comment by sbwhitney** [comment]
> @sbwhitney Thanks for the reply.
> 
> Can you explain?
> 
> Do you mean to use the server (for example with post_json) but to build the model with the fhir.resources package?

We don’t use the server component but another option would be to package up the python wheel file and host it internally using an internal repository like jfrog artifactory.

**Comment by emil45** [comment]
I've just got the last and the most important question, if I install it in an alternative way, jfrog/git-tag,
Is the version ready for production? Can I use it safely?

**Comment by sbwhitney** [comment]
> I've just got the last and the most important question, if I install it in an alternative way, jfrog/git-tag,
> Is the version ready for production? Can I use it safely?

Frankly, I'm glad that we no longer use it altogether as it appears all support has been ceased.

**Comment by Cyrusrome22** [comment]
Hi everyone, is there any news about this?

**Comment by iain-henderson** [comment]
Is this still dead?  It would be handy to not have to re-implement an existing library.

**Comment by hsolbrig** [comment]
It's not dead yet!   We worked on a fork about a year back and ran out of resources and funding.  See:  https://github.com/hsolbrig/client-py  .   Funding just arrived ...

**Comment by junchaohu** [comment]
Any update on this (pip install)?

If not, how could we manually install this to support R4?

Thanks.

**Comment by sbelhareth3** [comment]
I would like to bump this as well. The Georgia Tech Research Institute (GTRI) has an active involvement in many FHIR-related projects, and I am sure I convince some researchers to help if those in charge of this project could get in touch with me

**Comment by Potatochurchman** [comment]
> Any update on this (pip install)?
> 
> If not, how could we manually install this to support R4?
> 
> Thanks.

You can just do this to install fhirclient 4.0.0 manually:
`git clone https://github.com/smart-on-fhir/client-py.git`
`cd client-py`
`pip install -r requirements.txt`
`python setup.py sdist`
`cd dist`
`pip install fhirclient-4.0.0-py2.py3-none-any.whl`

Now type `pip list` and you should see fhirclient 4.0.0

**Comment by palfrey** [comment]
> It's not dead yet! We worked on a fork about a year back and ran out of resources and funding. See: https://github.com/hsolbrig/client-py . Funding just arrived ...

How's that going @hsolbrig? Is there any known timelines for a 4.0.0 release?

**Comment by hsolbrig** [comment]
Not yet -- it is amazing how much time can elapse between the award paperwork and the actual award.  Apologies --

**Comment by jeremyxia** [comment]
> requirements.txt



> > Any update on this (pip install)?
> > If not, how could we manually install this to support R4?
> > Thanks.
> 
> You can just do this to install fhirclient 4.0.0 manually (reference: https://github.com/smart-on-fhir/client-py#building-distribution):
> `git clone https://github.com/smart-on-fhir/client-py.git`
> `cd client-py`
> `pip install -r requirements.txt`
> `python setup.py sdist`
> `cd dist`
> `pip install fhirclient-4.0.0-py2.py3-none-any.whl`
> 
> Now type `pip list` and you should see fhirclient 4.0.0

pip install fhirclient-4.0.0-py2.py3-none-any.whl  This line doesn't work for me. I don't have .whl file. Any suggestion?

**Comment by Potatochurchman** [comment]
> > requirements.txt
> 
> > > Any update on this (pip install)?
> > > If not, how could we manually install this to support R4?
> > > Thanks.
> > 
> > 
> > You can just do this to install fhirclient 4.0.0 manually (reference: https://github.com/smart-on-fhir/client-py#building-distribution):
> > `git clone https://github.com/smart-on-fhir/client-py.git`
> > `cd client-py`
> > `pip install -r requirements.txt`
> > `python setup.py sdist`
> > `cd dist`
> > `pip install fhirclient-4.0.0-py2.py3-none-any.whl`
> > Now type `pip list` and you should see fhirclient 4.0.0
> 
> pip install fhirclient-4.0.0-py2.py3-none-any.whl This line doesn't work for me. I don't have .whl file. Any suggestion?

I'm sorry. I forgot to add one command (python setup.py bdist_wheel)
It should work now.

**Comment by MM-Lehmann** [comment]
much easier: `pip install -e git+https://github.com/smart-on-fhir/client-py#egg=fhirclient`

**Comment by pete88b** [comment]
In case anyone needs fhirclient as a setuptools requirement, `fhirclient@git+https://github.com/smart-on-fhir/client-py` worked for me

**Comment by chris-umed** [comment]
@hsolbrig If contributors are needed to get this project back up and running let me know. Happy to contribute and get others involved and I am sure all the commenters above might even be happy to contribute.

**Comment by hsolbrig** [comment]
Excellent news -- grant just came through.  Let's set up a session to figure out how best to get this running!

**Comment by pete88b** [comment]
@hsolbrig This is great (o: please count me in

**Comment by gitpushdashf** [comment]
We could use this as well. Thank you!

**Comment by bwalsh** [comment]
Any update ?

**Comment by honDhan** [comment]
would love to help add 4.0.0 to pip!

**Comment by aadejare** [comment]
Great. Would the FHIR protocols be up to date?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Minitour** [comment]
@hsolbrig Any updates on this thread? it has been over more than a year since this was last addressed.

**Comment by ebrahimebrahim** [comment]
As a workaround until the package is updated on PyPI, the following worked for me to get, at the time of writing this, the 4.0.0 version:
```sh
pip install git+https://github.com/smart-on-fhir/client-py.git
```

**Comment by RafaelWO** [comment]
It seems that it's back on PyPI again :tada: 

```
pip install fhirclient==4.1.0
```

https://github.com/smart-on-fhir/client-py/releases/tag/v4.1.0
https://pypi.org/project/fhirclient/
