### ISSUE TITLE
SyntaxError: invalid syntax in /beaker/synchronization.py

### ISSUE THREAD

**Issue by adolph** [smart-on-fhir/client-py#72]
The requirements_flask_app.txt specifies Beaker==1.7.0. When I attempt to run the Flask app using this Beaker version I get a syntax error, as seen below. After performing pip install --update beaker, the latest version of Beaker 1.10.0 does not have this issue.

  File "/Users/artrudeau/client-py/env/lib/python3.7/site-packages/beaker/synchronization.py", line 289
    self.async = 0
             ^
SyntaxError: invalid syntax

**Comment by Prolasis** [comment]
Thank you , modifying the requirement to 1.10.0 fixed my issue too

**Comment by akiikius** [comment]
Where can i find this file so i can update it? I am having the same problem.

**Comment by pete88b** [comment]
I updated requirements_flask_app.txt to have `Beaker==1.10.0` and ran `pip install -r requirements_flask_app.txt` again.

Hope this helps someone but ... I'm still blocked by https://github.com/smart-on-fhir/client-py/issues/86
