### ISSUE TITLE
Authorization error: invalid state

### ISSUE THREAD

**Issue by msniec** [smart-on-fhir/client-py#73]
Hi

I'm trying to set up example flask app but when I authorize with [http://launch.smarthealthit.org/v/r2/fhir](http://launch.smarthealthit.org/v/r2/fhir) I get invalid state response. I'm using version 1.0.3 of client-py to match FHIR version. 
<img width="574" alt="Zrzut ekranu 2019-06-27 o 10 31 29" src="https://user-images.githubusercontent.com/45016936/60250352-c2c2be80-98c6-11e9-8853-63aec6d78d87.png">

**Comment by mikix** [comment]
Does this still happen using modern code & servers? I'm going to optimistically close.
