### ISSUE TITLE
ValueSet.expansion.identifier is not optional?

### ISSUE THREAD

**Issue by yunwwang** [smart-on-fhir/client-py#75]
I got this error while creating a ValueSet expansion:

```
fhirclient.models.fhirabstractbase.FHIRValidationError: {root}:
  'Property "identifier" on <fhirclient.models.valueset.ValueSetExpansion object at 0x10392e410> is not optional, you must provide a value for it'
```

```ValueSet.expansion.identifier``` has cardinality ```0..1``` (http://build.fhir.org/valueset.html). It is optional.

**Comment by p2** [comment]
Which version are you using? ValueSetExpansion.identifier was `1..1` in STU-3 and is `0..1` in R4. I can create a ValueSetExpansion without identifier just fine with top of tree `master`.

**Comment by yunwwang** [comment]
I installed fhirclient using ```python3 -m pip install fhirclient```
```python3 -m pip list``` shows ```fhirclient        3.2.0```

**Comment by p2** [comment]
Version `3.2.0` is for STU-3, see here: https://github.com/smart-on-fhir/client-py#smart-fhir-client

Also refer to #70

**Comment by yunwwang** [comment]
I tried ```python3 -m pip install fhirclient==4.0.0``` and got error
```
  ERROR: Could not find a version that satisfies the requirement fhirclient==4.0.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.5.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 3.0.0, 3.1.0, 3.2.0)
ERROR: No matching distribution found for fhirclient==4.0.0
```
