### ISSUE TITLE
First example, "Read Data from Server" does not work

### ISSUE THREAD

**Issue by jayurbain** [smart-on-fhir/client-py#77]
First example, "Read Data from Server" does not work

from fhirclient import client
settings = {
    'app_id': 'my_web_app',
    'api_base': 'https://fhir-open-api-dstu2.smarthealthit.org'
}
smart = client.FHIRClient(settings=settings)

import fhirclient.models.patient as p
patient = p.Patient.read('hca-pat-1', smart.server)
patient.birthDate.isostring
# '1963-06-12'
smart.human_name(patient.name[0])
# 'Christy Ebert'

Error ---
ConnectionError: HTTPSConnectionPool(host='fhir-open-api-dstu2.smarthealthit.org', port=443): Max retries exceeded with url: /Patient/hca-pat-1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110b47978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

This works:
curl -X GET -H "Accept: application/json" http://test.fhir.org/r4/Patient/1

# http://test.fhir.org/r4/Patient/1
from fhirclient import client
settings = {
     'app_id': 'my_web_app',
     'api_base': 'http://test.fhir.org/r4'
}
smart = client.FHIRClient(settings=settings)
 
import fhirclient.models.patient as p
patient = p.Patient.read('1', smart.server)
patient.birthDate.isostring
smart.human_name(patient.name[0])

# 'Peter James Chalmers2'

**Comment by p2** [comment]
https://test.fhir.org/r3
https://test.fhir.org/r4

See #38
