### ISSUE TITLE
Unable to Loop Bundles

### ISSUE THREAD

**Issue by hbanh7** [smart-on-fhir/client-py#85]
I can't seem to figure out how to loop BundleEntries for a Bundle when using fhirclient. The Bundle object itself is not iterable. Any guidance or support would be much appreciated.

**Comment by mikix** [comment]
The README provides an example of this:

```
bundle = search.perform(smart.server)
print({entry.resource.resource_type for entry in bundle.entry})
# {'Encounter', 'Patient', 'Procedure'}
```

Does that work for you? Optimistically closing, but please re-open or ask more questions.
