### ISSUE TITLE
Flask app still failing on non-optional property 'type'

### ISSUE THREAD

**Issue by mgold99** [smart-on-fhir/client-py#86]
Unable to run demo flask app. seems to be a validation issue? thanks!

version: repo cloned and built today (22-Jun-20)

smart_defaults = {
    'app_id': 'my_web_app',
    'api_base': 'https://launch.smarthealthit.org/v/r4/fhir',
    'redirect_uri': 'http://localhost:8000/fhir-app/',
}

it also fails against this api_base - https://r4.smarthealthit.org

The error: 
models.fhirabstractbase.FHIRValidationError: {root}:
  rest.0:
    resource.70:
      searchParam.14:
        'Non-optional property "type" on <models.capabilitystatement.CapabilityStatementRestResourceSearchParam object at 0x7f8367dd19d0> is missing'

This appears to be similar to this closed issue: https://github.com/smart-on-fhir/client-py/issues/65

**Comment by Chesterguan** [comment]
I have tried all of the base paths from [Smart App Launcher](https://launch.smarthealthit.org/?auth_error=&fhir_version_1=r4&fhir_version_2=r4&iss=&launch_ehr=1&launch_url=&patient=&prov_skip_auth=1&provider=&pt_skip_auth=1&public_key=&sb=&sde=&sim_ehr=1&token_lifetime=15&user_pt=) with flask_app demo, but all of them are not working with couple of different problem shown below:
```
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))
```
```
      searchParam.14:
        'Non-optional property "type" on <models.capabilitystatement.CapabilityStatementRestResourceSearchParam object at 0x113508f40> is missing'
```
```models.fhirabstractbase.FHIRValidationError: {root}:
  rest.0:
    operation.0:
      definition:
        Wrong type <class 'dict'> for property "definition" on <class 'models.capabilitystatement.CapabilityStatementRestResourceOperation'>, expecting <class 'str'>
    resource.0:
      profile:
        Wrong type <class 'dict'> for property "profile" on <class 'models.capabilitystatement.CapabilityStatementRestResource'>, expecting <class 'str'>
  Superfluous entry "acceptUnknown" in data for <models.capabilitystatement.CapabilityStatement object at 0x10e9d6cd0>
```

**Comment by pete88b** [comment]
I've just started working on https://github.com/pete88b/smart-on-fhir-client-py-demo to hopefully help people get started with the python FHIR client - working flask app included (o:

although ... it might be hard to keep it working as FHIR servers and the python client project make changes ...

**Comment by dogversioning** [comment]
This looks like it's a configuration issue with https://r4.smarthealthit.org/ and that error message is correct - we're going to address it on that side.
