### ISSUE TITLE
Demo example in the README doesn't work

### ISSUE THREAD

**Issue by bioteamMichael** [smart-on-fhir/client-py#87]
I just installed fhirclient for python3, and when I run the demo code and try to connect to https://fhir-open-api-dstu2.smarthealthit.org, it throws an error when I try to do the call to p.Patient.read():

> ConnectionError: HTTPSConnectionPool(host='fhir-open-api-dstu2.smarthealthit.org', port=443): Max retries exceeded with url: /Patient/hca-pat-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b7458d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

**Comment by palfrey** [comment]
Probably fixed by https://github.com/smart-on-fhir/client-py/pull/83

**Comment by t2ac32** [comment]
Same problem, with pip install 17/Oct/2020. #83  not merged yet.

**Comment by jeremyxia** [comment]
I tried and have same problem. Anyone can get demo example to work?

**Comment by pete88b** [comment]
I've just started working on https://github.com/pete88b/smart-on-fhir-client-py-demo to hopefully help people get started with the python FHIR client
