### ISSUE TITLE
Need SNI support in client

### ISSUE THREAD

**Issue by nschwertner** [smart-on-fhir/client-py#9]
It looks like Requests (used in the Python client) needs some additional modules in order to support SNI (we have multiple certificats served on the same IP). https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484 Otherwise, the client throws an SSLError (hostname 'stub.smarthealthit.org' doesn't match either of '*.smartplatforms.org', 'smartplatforms.org') when pointed at a API server that is on a host with multiple certificates.

The test case is running any Python-based sample app against https://stub.smarthealthit.org/smart/dstu2 (for example using the launcher at https://stub.smarthealthit.org/). This service will not work for self-launched apps that ask for context. Works for apps that are launched in context (via the launcher at https://stub.smarthealthit.org/ or similar) and with apps that don't need context. The sample app that comes with the Python client is a standalone app that needs context assigned after launch, so not good for testing. We have another sample app that needs to be launched in context and should work for testing purposes: https://github.com/smart-on-fhir/sample-apps/blob/master/rest-app/app.py

**Comment by p2** [comment]
As discussed, this is fixed on the Python level with Python 2.7.9+ and in Python 3.
