### ISSUE TITLE
convert XML to FHIR data

### ISSUE THREAD

**Issue by challavamsi** [smart-on-fhir/client-py#95]
Hi I am a newbie to FHIR data formats. This might be a dumb questions as well,  is there any easy way to convert bunch of XML's to FHIR format? any suggestions on  blog/tutorials for reference?

Any help is appreciated!!

**Comment by mikix** [comment]
You mean from FHIR XML to FHIR JSON? Or something else?

If it's from xml representation to json representation, then there is a [website](https://fhir-formats.github.io/) as well as [various tools](https://duckduckgo.com/?t=ffab&q=fhir+xml+to+json&ia=web).

I know this is an old question and you probably found a solution in the intervening years. :smile:
